### ISSUE TITLE
Add functionality to serve up rendered doc only

### ISSUE THREAD

**Issue by kitsonk** [phiggins42/rstwiki#22]
rstwiki should be able to serve up content only document for embedding in other solutions (e.g. API Viewer).  The rendering should not contain only HTML markup.

**Comment by phiggins42** [comment]
... it almost already can. the (maybe old?) built-in preview editor POSTS content and returns template-less rendering of content.

**Comment by kitsonk** [comment]
Ok, I will take a look.  I thought there was something in there, but I hadn't looked at it specifically yet, it was more of reminder to myself based on a conversations with @wkeese.

**Comment by kitsonk** [comment]
Would we want this to be a special static set of documents, or served up on demand from an instance of rstWiki?

**Comment by wkeese** [comment]
I thought it would be static docs... actually the API viewer currently needs static docs because it has a heuristic algorithm for matching the API page to the reference doc page, and the algorithm requires quickly getting a listing of all the reference doc pages available.   In other words it uses PHP's file API to check what pages exist.
